'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ExternalLink, Save } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { defaultLayout, homepageSections, normalizeLayout, type SectionVisibility, findSection } from '@/lib/admin/sections';
import { invalidateContent } from '@/lib/content-cache';
import { useUnsavedWarning } from '@/components/admin/ContentEditor';
export default function Website(){
 const [layout,setLayout]=useState<SectionVisibility[]>(defaultLayout);const [original,setOriginal]=useState('');const [ready,setReady]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const dirty=ready&&JSON.stringify(layout)!==original;useUnsavedWarning(dirty);
 async function load(){setError('');try{const res=await apiFetch('/api/content?key=site_layout',{cache:'no-store'});if(!res.ok)throw Error('Could not load visibility settings.');const data=await res.json();const next=normalizeLayout(data.sections);setLayout(next);setOriginal(JSON.stringify(next));setReady(true);}catch(err){setError(err instanceof Error?err.message:'Unable to connect.');}}
 useEffect(()=>{void load();},[]);
 async function save(){setSaving(true);setError('');try{const res=await apiFetch('/api/content',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'site_layout',data:{sections:layout}})});if(!res.ok)throw Error('Could not publish visibility settings.');invalidateContent('site_layout');setOriginal(JSON.stringify(layout));setMessage('Homepage visibility updated.');}catch(err){setError(err instanceof Error?err.message:'Unable to publish.');}finally{setSaving(false);}}
 return <><div className="admin-page-heading"><div><div className="admin-eyebrow">Build a considered first impression</div><h1 className="admin-heading">Homepage & sections</h1><p className="admin-description">Your current homepage, from top to bottom. Edit the content or choose which sections visitors see.</p></div><a href="/" target="_blank" rel="noreferrer" className="admin-button"><ExternalLink/>View homepage</a></div>
 {error&&<div role="alert" className="admin-notice error">{error}{!ready&&<button onClick={load} className="underline ml-2">Try again</button>}</div>}{message&&<p className="admin-notice" role="status">{message}</p>}
 <div className="admin-editor-grid"><div className="admin-panel"><div className="admin-panel-header"><h2>Homepage sections</h2><span className="admin-muted">{ready?`${layout.filter(item=>item.visible).length} of ${layout.length} visible`:'Loading visibility…'}</span></div>{homepageSections.map((item,index)=>{const visible=layout.find(entry=>entry.id===item.id)?.visible;const section=findSection(item.id);return <div className="admin-section-row" key={item.id}><span className="admin-number">{String(index+1).padStart(2,'0')}</span><div className="admin-row-copy"><strong>{item.title}</strong><p>{section?.description||(item.id==='products'?'Connected to your product catalog':'Customer contact form and lead collection')}</p></div><span className={`admin-badge ${!visible?'gray':''}`}>{visible?'Visible':'Hidden'}</span><button className="admin-toggle" role="switch" aria-label={`Show ${item.title}`} aria-checked={!!visible} disabled={!ready||saving} onClick={()=>{setLayout(prev=>prev.map(entry=>entry.id===item.id?{...entry,visible:!entry.visible}:entry));setMessage('');}}><span/></button>{item.id!=='inquiry'&&<Link className="admin-row-link" href={item.id==='products'?'/admin/products':`/admin/website/${item.id}`} aria-label={`Edit ${item.title}`}><ArrowUpRight/></Link>}</div>;})}</div><aside className="admin-panel admin-help"><h3>A clear view of your website.</h3><p>These sections match the current homepage. Hidden sections keep their content so you can bring them back later.</p><h3>More website content</h3><Link className="admin-row-link mb-4" href="/admin/website/gallery">Gallery page<ArrowUpRight/></Link><Link className="admin-row-link mb-4" href="/admin/blogs">Blog & news<ArrowUpRight/></Link><Link className="admin-row-link" href="/admin/website/footer">Footer & contact details<ArrowUpRight/></Link><p className="mt-6">The navigation and footer stay available so visitors can always find their way.</p></aside></div><div className="admin-savebar"><span className="admin-muted">{dirty?'Visibility changes are not published yet.':'Choose a section to edit or change its visibility.'}</span><button className="admin-button primary" disabled={!dirty||saving} onClick={save}><Save/>{saving?'Publishing…':'Publish visibility'}</button></div></>;
}
