'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Package, Inbox, FileText, PanelsTopLeft, Plus, ExternalLink } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { homepageSections } from '@/lib/admin/sections';
export default function Dashboard(){
  const [data,setData]=useState<{products:any[];inquiries:any[];articles:any[]}|null>(null);const [error,setError]=useState('');
  async function load(){setError('');try{const results=await Promise.all(['/api/products','/api/inquiries','/api/articles'].map(async path=>{const res=await apiFetch(path,{cache:'no-store'});if(!res.ok)throw Error('Unable to load workspace data. Check that the backend is available.');const json=await res.json();if(!Array.isArray(json))throw Error('Unexpected response from the server.');return json;}));setData({products:results[0],inquiries:results[1],articles:results[2]});}catch(err){setError(err instanceof Error?err.message:'Could not load data.');}}
  useEffect(()=>{void load();},[]);
  const pending=data?.inquiries.filter(item=>!item.status||item.status==='Pending').length;
  return <><div className="admin-page-heading"><div><div className="admin-eyebrow">Your workspace at a glance</div><h1 className="admin-heading">Website overview</h1><p className="admin-description">Keep your catalog current, your content fresh, and your customers connected.</p></div><a href="/" target="_blank" rel="noreferrer" className="admin-button"><ExternalLink/>View website</a></div>
    <div className="admin-welcome"><div><div className="admin-eyebrow">Made for your next chapter</div><h2>A better experience starts here.</h2><p>Manage the sections your customers see, in the same order as your homepage.</p></div><Link href="/admin/website" className="admin-button primary">Manage homepage<ArrowRight/></Link></div>
    {error&&<div role="alert" className="admin-notice error">{error} <button onClick={load} className="underline ml-2">Try again</button></div>}
    <div className="admin-stats">{[{title:'Products',value:data?.products.length,caption:'In your catalog',icon:Package,href:'/admin/products'},{title:'New inquiries',value:pending,caption:'Awaiting a response',icon:Inbox,href:'/admin/inquiries'},{title:'Articles',value:data?.articles.length,caption:'Stories & company updates',icon:FileText,href:'/admin/blogs'},{title:'Homepage sections',value:homepageSections.length,caption:'Content & visibility controls',icon:PanelsTopLeft,href:'/admin/website'}].map(item=><Link key={item.title} href={item.href} className="admin-stat"><div className="admin-stat-top">{item.title}<item.icon/></div><strong>{item.value??'—'}</strong><small>{item.caption}</small></Link>)}</div>
    <div className="admin-grid"><div className="admin-panel"><div className="admin-panel-header"><h2>Recent inquiries</h2><Link href="/admin/inquiries" className="admin-row-link">View all<ArrowUpRight/></Link></div>{data?.inquiries.length?<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Customer</th><th>Interested in</th><th>Status</th></tr></thead><tbody>{data.inquiries.slice(0,5).map(item=><tr key={item._id||item.id}><td><strong>{item.name}</strong><div className="admin-muted">{item.company||item.email}</div></td><td>{item.skuProfile||'General inquiry'}</td><td><span className={`admin-badge ${item.status==='Completed'?'':item.status==='Contacted'?'gray':'orange'}`}>{item.status||'Pending'}</span></td></tr>)}</tbody></table></div>:<div className="admin-empty">{data?'New customer inquiries will appear here.':error?'Inquiry data is unavailable.':'Loading inquiries…'}</div>}</div>
    <div className="admin-panel"><div className="admin-panel-header"><h2>Quick actions</h2><span className="admin-muted">Make it happen</span></div>{[{title:'Add a product',text:'Expand your packaging catalog',href:'/admin/products/new',icon:Package},{title:'Write an article',text:'Share news and useful insights',href:'/admin/blogs/new',icon:FileText},{title:'Update your homepage',text:'Edit sections and visibility',href:'/admin/website',icon:PanelsTopLeft}].map(item=><Link className="admin-section-row" href={item.href} key={item.href}><item.icon size={19} className="text-violet-500"/><div className="admin-row-copy"><strong>{item.title}</strong><p>{item.text}</p></div><Plus size={15} className="text-gray-400"/></Link>)}</div></div>
    <div className="admin-panel mt-6"><div className="admin-panel-header"><h2>Your homepage, section by section</h2><Link href="/admin/website" className="admin-row-link">Manage all<ArrowUpRight/></Link></div><div className="grid md:grid-cols-2">{homepageSections.slice(0,6).map((item,index)=><Link className="admin-section-row" href={item.id==='products'?'/admin/products':`/admin/website/${item.id}`} key={item.id}><span className="admin-number">{String(index+1).padStart(2,'0')}</span><strong className="admin-row-copy">{item.title}</strong><ArrowUpRight size={14} className="text-gray-400"/></Link>)}</div></div>
  </>;
}
