export const initialProducts = [
  // --- LABELS ---
  {
    id: "plain-labels",
    title: "Plain Labels",
    category: "labels",
    tag: "Plain",
    blurb: "Unprinted plain paper labels for barcodes and shipping.",
    longDesc: "Premium white matte transfer labels designed for high-clarity barcode printing. Features a strong permanent hot-melt adhesive that bonds instantly to corrugated boxes, poly bags, and plastic wrap, ensuring zero label lift during parcel transit.",
    basePrice: "₹180 / Roll",
    image: "/images/products/plain-labels/image.png",
    gallery: ["/images/products/plain-labels/image.png"],
    specs: {
      "Material Type": "Matte Chromo Paper",
      "Adhesive Style": "Permanent Hot-Melt",
      "Core Diameter": "1 inch / 3 inch",
      "Supported Printers": "Zebra, TSC, Honeywell",
    },
    options: {
      widths: ["50 mm", "100 mm"],
      thicknesses: ["80 GSM"],
      colors: ["Pure White"],
    },
    applications: ["E-commerce shipping labels", "Warehouse barcode sticker", "Inventory box labeling"],
    visualGradients: "from-amber-400 to-orange-500",
  },
  {
    id: "printed-labels",
    title: "Printed Labels",
    category: "labels",
    tag: "Printed",
    blurb: "Bespoke custom-printed labels with company branding.",
    longDesc: "High-fidelity flexographic and digital printing options for product packaging. We print with UV-resistant inks on paper or plastic films, ensuring your brand graphics remain crisp, bright, and moisture-resistant.",
    basePrice: "₹0.50 / Sticker",
    image: "/images/products/printed-labels/image.png",
    gallery: ["/images/products/printed-labels/image.png"],
    specs: {
      "Print Resolution": "Up to 1200 DPI",
      "Material Base": "Chromo Paper / Glossy PP Film",
      "Lamination": "Glossy / Matte UV top-coat",
      "Roll Direction": "Outward facing",
    },
    options: {
      widths: ["Custom sizes"],
      thicknesses: ["90 GSM"],
      colors: ["Multicolor Custom CMYK"],
    },
    applications: ["Cosmetics branding", "Food item jars", "Promotional packaging seal"],
    visualGradients: "from-amber-400 to-orange-500",
  },
  {
    id: "barcode-labels",
    title: "Barcode Labels",
    category: "labels",
    tag: "Barcode",
    blurb: "High-density thermal transfer barcode sticker labels.",
    longDesc: "Premium thermal transfer and direct thermal labels configured with precise gap spacing. Offers high scannability rates under commercial red-laser and imaging scanners, optimized for logistics sorting lines.",
    basePrice: "₹210 / Roll",
    image: "/images/products/barcode-labels/image.png",
    gallery: ["/images/products/barcode-labels/image.png"],
    specs: {
      "Gap Spacing": "2mm standard",
      "Format": "Die-cut roll",
      "Liner Type": "Glassine backing paper",
      "Read Rate": "99.9% scanner compliance",
    },
    options: {
      widths: ["38x25 mm", "50x25 mm", "100x150 mm"],
      thicknesses: ["85 GSM"],
      colors: ["Bright White"],
    },
    applications: ["Product code stickers", "Asset tracking tags", "Supermarket pricing stickers"],
    visualGradients: "from-amber-400 to-orange-500",
  },
  {
    id: "product-labels",
    title: "Product Labels",
    category: "labels",
    tag: "Product",
    blurb: "Premium glossy product labels for retail items.",
    longDesc: "Designed to elevate retail presence. Printed on high-tensile polypropylene film to resist scratching, moisture, oil, and refrigeration. Gives a premium hand-feel with rich glossy finishes.",
    basePrice: "₹0.75 / Sticker",
    image: "/images/products/product-labels/image.png",
    gallery: ["/images/products/product-labels/image.png"],
    specs: {
      "Substrate": "Premium BOPP Film",
      "Water Resistance": "100% waterproof",
      "Glue Type": "Acrylic emulsion non-residue",
      "Finish Options": "Gold foil / Embossed details",
    },
    options: {
      widths: ["Custom sizes"],
      thicknesses: ["60 Micron Film"],
      colors: ["High Gloss Custom Color"],
    },
    applications: ["Beverage bottles", "Squeeze tube packaging", "Premium retail boxes"],
    visualGradients: "from-amber-400 to-orange-500",
  },
  {
    id: "self-adhesive-labels",
    title: "Self Adhesive Labels",
    category: "labels",
    tag: "Self Adhesive",
    blurb: "Pressure-sensitive permanent adhesive sticker labels.",
    longDesc: "All-weather self-adhesive label rolls designed with high tack shear. Applies smoothly without bubbling on glass, plastics, metals, and papers, ensuring structural integrity over long shelf life storage.",
    basePrice: "₹190 / Roll",
    image: "/images/products/self-adhesive-labels/image.png",
    gallery: ["/images/products/self-adhesive-labels/image.png"],
    specs: {
      "Adhesion Tack": "High permanent bonding",
      "Application Temp": "10°C to 45°C",
      "Working Temp Range": "-20°C to 80°C",
      "Dispensing compatibility": "Automatic label applicators",
    },
    options: {
      widths: ["4 inch", "6 inch"],
      thicknesses: ["82 GSM"],
      colors: ["White", "Yellow", "Clear transparent"],
    },
    applications: ["Chemical drum warning sticker", "Logistics dispatch tags", "Carton shipping seals"],
    visualGradients: "from-amber-400 to-orange-500",
  },
  {
    id: "thermal-labels",
    title: "Thermal Labels",
    category: "labels",
    tag: "Thermal",
    blurb: "Direct thermal stickers for fast printing without ink.",
    longDesc: "Thermal paper rolls coated with high-sensitivity black dye. Prints without ribbon in direct thermal printers, lowering print overhead for e-commerce dispatch hubs and weight scale printers.",
    basePrice: "₹160 / Roll",
    image: "/images/products/thermal-labels/image.png",
    gallery: ["/images/products/thermal-labels/image.png"],
    specs: {
      "Printing Mechanism": "Direct Thermal (No ribbon required)",
      "Heat Sensitivity": "Standard high contrast",
      "Top-coat style": "Wax coated moisture shield",
      "Core Size": "1.5 inch standard",
    },
    options: {
      widths: ["3x2 inches", "4x6 inches"],
      thicknesses: ["78 GSM"],
      colors: ["White"],
    },
    applications: ["Quick dispatch labels", "Weigh scale weight tags", "Visitor badge printing"],
    visualGradients: "from-amber-400 to-orange-500",
  },

  // --- FILMS, BAGS & TUBES ---
  {
    id: "pof-shrink-rolls",
    title: "POF Shrink Rolls & Pouches",
    category: "films-bags-tubes",
    tag: "POF",
    blurb: "Cross-linked polyolefin shrink wrapping film and pre-cut pouches.",
    longDesc: "Co-extruded five-layer cross-linked POF shrink film. Provides outstanding tensile strength, ultra-clear optics, and high shrink ratios. Best suited for retail multi-packs, toys, books, and food items.",
    basePrice: "₹3,800 / Roll",
    image: "/images/products/pof-shrink-rolls/image.png",
    gallery: ["/images/products/pof-shrink-rolls/image.png"],
    specs: {
      "Material Structure": "5-Layer Co-extruded POF",
      "Shrink Ratio": "62% MD / 60% TD",
      "Sealing Temperature": "140°C - 180°C",
      "Clarity Level": "93% high gloss reflection",
    },
    options: {
      widths: ["300 mm", "450 mm", "600 mm"],
      thicknesses: ["15 Micron", "19 Micron", "25 Micron"],
      colors: ["Ultra Clear"],
    },
    applications: ["FMCG packs", "Cosmetics boxes", "Stationery packs"],
    visualGradients: "from-sky-400 to-blue-500",
  },
  {
    id: "ldpe-shrink-rolls",
    title: "LDPE Shrink Rolls & Pouches",
    category: "films-bags-tubes",
    tag: "LDPE",
    blurb: "Heavy-duty low-density polyethylene shrink rolls for heavy bundling.",
    longDesc: "High gauge LDPE collation shrink film. Delivers maximum puncture resistance and load-holding strength. Engineered to wrap heavy packs of soft drink cans, mineral water bottles, and glass jars without cartons.",
    basePrice: "₹185 / kg",
    image: "/images/products/ldpe-shrink-rolls/image.png",
    gallery: ["/images/products/ldpe-shrink-rolls/image.png"],
    specs: {
      "Polymer Density": "0.92 g/cm³ LDPE",
      "Shrink Temp range": "160°C to 200°C",
      "Dart Impact Limit": "120g average",
      "Recyclability": "Category 4 LDPE Recyclable",
    },
    options: {
      widths: ["500 mm", "800 mm", "1200 mm"],
      thicknesses: ["50 Micron", "80 Micron", "120 Micron"],
      colors: ["Translucent Clear"],
    },
    applications: ["Beverage bottle collation packaging", "Heavy tile and brick bundling", "Logistics bulk packs"],
    visualGradients: "from-sky-400 to-blue-500",
  },
  {
    id: "pvc-shrink-rolls",
    title: "PVC Shrink Rolls, Pouches & Tubes",
    category: "films-bags-tubes",
    tag: "PVC",
    blurb: "Clear PVC heat shrinkable sleeves, rolls and profile tubes.",
    longDesc: "High gloss polyvinyl chloride shrink film offering low temperature shrink properties. Excellent for cap seals, tamper-evident neck bands, and promotional pack bundling.",
    basePrice: "₹240 / kg",
    image: "/images/products/pvc-shrink-rolls/image.png",
    gallery: ["/images/products/pvc-shrink-rolls/image.png"],
    specs: {
      "Shrink Speed": "Fast low-temp activation",
      "Shrink Ratio": "45% MD / 50% TD",
      "Optics": "High gloss clarity",
      "Format Types": "Tubular roll / Pre-cut sleeves / Pouches",
    },
    options: {
      widths: ["50 mm", "150 mm", "300 mm"],
      thicknesses: ["35 Micron", "40 Micron", "50 Micron"],
      colors: ["Glass Clear"],
    },
    applications: ["Jar neck bands", "Printed sleeve labels", "Battery pack wrap"],
    visualGradients: "from-sky-400 to-blue-500",
  },
  {
    id: "poly-courier-bags",
    title: "Poly Courier Bags",
    category: "films-bags-tubes",
    tag: "Poly Bag",
    blurb: "Tamper-evident co-extruded plastic courier mailing bags.",
    longDesc: "Manufactured from 60 Micron co-extruded white and black LDPE film. The interior is opaque black to prevent light transmission, while the exterior is bright white. Features a heavy-duty permanent hot-melt adhesive strip.",
    basePrice: "₹4.20 / Bag",
    image: "/images/products/poly-courier-bags/image.png",
    gallery: ["/images/products/poly-courier-bags/image.png"],
    specs: {
      "Film Density": "Double-layered co-ex 60 Micron",
      "Tear Strength": "High stretch threshold",
      "Closure Style": "Peel & Seal Hot-melt permanent strip",
      "Opacity": "100% block-out security",
    },
    options: {
      widths: ["10x12 inches", "12x16 inches", "16x20 inches"],
      thicknesses: ["60 Micron", "75 Micron"],
      colors: ["White/Black Co-ex"],
    },
    applications: ["E-commerce courier dispatch", "Document dispatch mailing", "Soft apparel shipments"],
    visualGradients: "from-sky-400 to-blue-500",
  },
  {
    id: "paper-courier-bags",
    title: "Paper Courier Bags",
    category: "films-bags-tubes",
    tag: "Paper Bag",
    blurb: "FSC certified recyclable heavy kraft paper dispatch bags.",
    longDesc: "Sustainable alternative to plastic mailers. Constructed from high-bursting strength virgin kraft paper, featuring a dual self-adhesive strip system for returns and an easy-open tear tape.",
    basePrice: "₹8.50 / Bag",
    image: "/images/products/paper-courier-bags/image.png",
    gallery: ["/images/products/paper-courier-bags/image.png"],
    specs: {
      "Paper Grade": "120 GSM Virgin Kraft",
      "Eco standard": "100% Biodegradable & Recyclable",
      "Adhesion tape": "Double tape strip for returns",
      "Tear strip": "Easy-open red thread pull strip",
    },
    options: {
      widths: ["Small (220x300mm)", "Medium (320x450mm)", "Large (400x520mm)"],
      thicknesses: ["120 GSM"],
      colors: ["Natural Brown Kraft"],
    },
    applications: ["Eco-friendly clothing dispatch", "Corporate document mailing", "Premium sustainable brand shipping"],
    visualGradients: "from-sky-400 to-blue-500",
  },
  {
    id: "specialty-pouches",
    title: "Specialty Pouches (PET G / BOPP / ESD)",
    category: "films-bags-tubes",
    tag: "Specialty",
    blurb: "PET-G shrink films, printed BOPP stand-up pouches and anti-static ESD pouches.",
    longDesc: "High-barrier pouches tailored for specific applications. Includes silver ESD shielding bags for electronics, high-shrink PET-G rolls for contour container branding, and multi-layer laminated stand-up pouches.",
    basePrice: "₹280 / kg",
    image: "/images/products/specialty-pouches/image.png",
    gallery: ["/images/products/specialty-pouches/image.png"],
    specs: {
      "Pouch Types": "ESD shielding / PET-G shrink / Laminated zipper stand-up",
      "ESD Surface Resistance": "10^8 to 10^11 ohms",
      "Barrier Properties": "High moisture and gas barrier options",
      "Printability": "Gravure custom print up to 9 colors",
    },
    options: {
      widths: ["Custom configurations"],
      thicknesses: ["50 to 120 Micron"],
      colors: ["Silver ESD", "Ultra Clear", "Custom graphics print"],
    },
    applications: ["Electronic PCB packaging", "Stand-up dry food pouches", "High-contour jar label sleeve wrap"],
    visualGradients: "from-sky-400 to-blue-500",
  },

  // --- STRAPPING ---
  {
    id: "pp-strap",
    title: "PP Strap",
    category: "strapping",
    tag: "PP STRAP",
    blurb: "Virgin grade polypropylene strapping bands for box reinforcement.",
    longDesc: "Virgin polypropylene strapping rolls designed for high friction weld joint efficiency. Excellent tracking in semi-automatic and automatic strapping machines, with minimal dust build-up on welding heads.",
    basePrice: "₹1,600 / Roll",
    image: "/images/products/pp-strap/image.png",
    gallery: ["/images/products/pp-strap/image.png"],
    specs: {
      "Material Grade": "Virgin Polypropylene",
      "Core Size": "200mm ID x 190mm Width",
      "Surface Finish": "Diamond embossed texture",
      "Joint Efficiency": "80% average friction-weld",
    },
    options: {
      widths: ["9 mm", "12 mm", "15 mm"],
      thicknesses: ["0.55 mm", "0.65 mm", "0.8 mm"],
      colors: ["White", "Semi-transparent"],
    },
    applications: ["Carton strapping reinforcement", "Newspaper bundle binding", "Light pallet stabilization"],
    visualGradients: "from-emerald-400 to-teal-500",
  },
  {
    id: "printed-pp-strap",
    title: "Printed PP Strap",
    category: "strapping",
    tag: "PRINTED PP",
    blurb: "Custom-branded printed strap rolls for security and branding.",
    longDesc: "Polypropylene strapping printed with customized corporate logos, brand names, or warnings. Serves as a double security seal to prevent tampering on dispatch boxes while building brand recognition.",
    basePrice: "₹1,850 / Roll",
    image: "/images/products/printed-pp-strap/image.png",
    gallery: ["/images/products/printed-pp-strap/image.png"],
    specs: {
      "Print ink style": "High-bonding ink (no rub-off)",
      "Print Length Cycle": "300mm repetition standard",
      "Embossing": "Light diamond print profile",
      "Breaking Load": "180 kg average",
    },
    options: {
      widths: ["12 mm", "15 mm"],
      thicknesses: ["0.65 mm", "0.8 mm"],
      colors: ["White with Blue print", "Yellow with Black print", "Custom base/ink colors"],
    },
    applications: ["High-value electronics dispatch", "Anti-pilferage secure packing", "Branded warehouse inventory packaging"],
    visualGradients: "from-emerald-400 to-teal-500",
  },
  {
    id: "colored-pp-strap",
    title: "Colored PP Strap",
    category: "strapping",
    tag: "COLORED PP",
    blurb: "High-visibility colored strapping bands for load categorization.",
    longDesc: "Vibrant solid colored polypropylene strapping. Extremely helpful for color-coding shipping boxes, pallet lots, or routing codes in large distribution centers.",
    basePrice: "₹1,750 / Roll",
    image: "/images/products/colored-pp-strap/image.png",
    gallery: ["/images/products/colored-pp-strap/image.png"],
    specs: {
      "Pigmentation Style": "High opacity color masterbatch",
      "Width Tolerance": "+/- 0.05 mm",
      "Strap Weight": "10 kg/roll average",
      "Coil length": "2000 meters standard",
    },
    options: {
      widths: ["12 mm", "15 mm"],
      thicknesses: ["0.65 mm", "0.8 mm"],
      colors: ["Signal Red", "Safety Yellow", "Ocean Blue", "Grass Green"],
    },
    applications: ["Logistics color coding", "Pallet batch grouping", "Industrial warehouse box marking"],
    visualGradients: "from-emerald-400 to-teal-500",
  },
  {
    id: "pet-strap",
    title: "PET Strap",
    category: "strapping",
    tag: "PET STRAP",
    blurb: "High-tensile polyester strapping band replacing steel bands.",
    longDesc: "Extruded heavy-duty PET strapping bands. Provides extremely high tension retention and impact absorption over long distance transits. Replacing steel strapping due to safer hand operation and rust-free features.",
    basePrice: "₹2,500 / Roll",
    image: "/images/products/pet-strap/image.png",
    gallery: ["/images/products/pet-strap/image.png"],
    specs: {
      "Core Size": "406mm ID x 150mm Width",
      "Tensile Strength": "480 kg average",
      "Elastic elongation": "12% - 15% shock recovery",
      "Rust proofing": "100% moisture and UV resistant",
    },
    options: {
      widths: ["12 mm", "15 mm", "19 mm"],
      thicknesses: ["0.6 mm", "0.8 mm", "1.0 mm"],
      colors: ["Emerald Green", "Jet Black"],
    },
    applications: ["Heavy pallet stabilization", "Steel and coil strapping", "Brick kiln block tying"],
    visualGradients: "from-emerald-400 to-teal-500",
  },

  // --- PROTECTIVE PACKAGING ---
  {
    id: "bubble-roll",
    title: "Bubble Roll & Pouches",
    category: "protective",
    tag: "Bubble",
    blurb: "Air bubble cushioning wrap rolls and custom anti-static pouches.",
    longDesc: "Cushioning bubble wrap rolls made from 100% virgin LDPE. Designed with heavy air sealing to prevent air leak. Ideal for fragile glassware, artwork, instruments, and electronics protection.",
    basePrice: "₹1,150 / Roll",
    image: "/images/products/bubble-roll/image.png",
    gallery: ["/images/products/bubble-roll/image.png"],
    specs: {
      "Bubble Size": "10mm bubble diameter",
      "Material Base": "Virgin LDPE (Recyclable)",
      "Standard Width": "1.0m / 1.5m",
      "Anti-static option": "Pink ESD additives available",
    },
    options: {
      widths: ["1.0m x 50m", "1.5m x 50m"],
      thicknesses: ["50 GSM", "80 GSM"],
      colors: ["Translucent Clear", "Anti-static Pink"],
    },
    applications: ["Glass packaging cushioning", "Electronics wrapping", "Fragile retail box packing"],
    visualGradients: "from-rose-400 to-pink-500",
  },
  {
    id: "epe-foam-rolls",
    title: "EPE Foam Rolls",
    category: "protective",
    tag: "EPE Foam",
    blurb: "Expanded polyethylene foam cushioning rolls for surface protection.",
    longDesc: "Non-crosslinked, closed-cell EPE foam sheets providing premium cushioning and shock absorption. Prevents scratch marks on painted surfaces, sheet metal components, electronics, and glass plates.",
    basePrice: "₹1,250 / Roll",
    image: "/images/products/epe-foam-rolls/image.png",
    gallery: ["/images/products/epe-foam-rolls/image.png"],
    specs: {
      "Structure Style": "Closed-cell non-crosslinked foam",
      "Density": "20 kg/m³ average",
      "Scratch Shield": "100% scratch free protection",
      "Thermal Insulation": "Good thermal insulation limits",
    },
    options: {
      widths: ["1.0m x 100m"],
      thicknesses: ["1 mm", "2 mm", "5 mm", "10 mm"],
      colors: ["Cream White"],
    },
    applications: ["Automotive body sheet metal wrapping", "Precision electronics cushioning", "Premium furniture corner protector"],
    visualGradients: "from-rose-400 to-pink-500",
  },
  {
    id: "air-bags",
    title: "Air Bags",
    category: "protective",
    tag: "Air Bag",
    blurb: "Inflatable kraft and poly container dunnage air bags for load bracing.",
    longDesc: "Heavy-duty inflatable dunnage air bags designed to brace cargo inside shipping containers. Prevents shifts and collisions during sea and rail transits, filling lateral voids between pallets.",
    basePrice: "₹450 / Piece",
    image: "/images/products/air-bags/image.png",
    gallery: ["/images/products/air-bags/image.png"],
    specs: {
      "Working Pressure": "Max 0.2 Bar",
      "Inner Liner": "Multi-layer co-extruded PE",
      "Outer Shell": "Heavy Kraft Paper / Woven Polypropylene",
      "Valve Style": "Quick-inflator high speed valve",
    },
    options: {
      widths: ["90 x 120 cm", "90 x 180 cm", "120 x 240 cm"],
      thicknesses: ["PP Woven Single Shift", "Kraft Paper 2-Ply"],
      colors: ["Brown Kraft", "White Poly"],
    },
    applications: ["Sea container cargo bracing", "Truck trailer pallet lock", "Rail cargo void filler"],
    visualGradients: "from-rose-400 to-pink-500",
  },
  {
    id: "corrugated-boxes",
    title: "Corrugated Boxes",
    category: "protective",
    tag: "Box",
    blurb: "Premium 3-ply, 5-ply and 7-ply kraft board shipping boxes.",
    longDesc: "High compression strength corrugated shipping boxes. Custom engineered flute patterns offer extreme load resistance under stacking storage. Clean printing finish for warehouse tracking codes.",
    basePrice: "₹85 / Box",
    image: "/images/products/corrugated-boxes/image.png",
    gallery: ["/images/products/corrugated-boxes/image.png"],
    specs: {
      "Compressive Limit": "380 kg stacking weight",
      "Bursting strength": "14.5 kg/cm²",
      "GSM Specification": "180 GSM Top Kraft / 150 GSM flutes",
      "Joint assembly": "Heavy-duty wire stitched / Glued seam",
    },
    options: {
      widths: ["Small (30x20x20cm)", "Medium (45x30x30cm)", "Large (60x40x40cm)"],
      thicknesses: ["3-Ply Single Wall", "5-Ply Double Wall", "7-Ply Heavy Duty"],
      colors: ["Kraft Brown", "Bleached White"],
    },
    applications: ["E-commerce warehouse dispatches", "Heavy components shipment", "Product retail box stacking"],
    visualGradients: "from-rose-400 to-pink-500",
  },
  {
    id: "corrugated-rolls",
    title: "Corrugated Rolls",
    category: "protective",
    tag: "Roll",
    blurb: "Flexible single-face corrugated paper rolls for shock wrap.",
    longDesc: "Single face corrugated wrapping paper in rolls. Highly flexible structure allows wrapping around irregular shape industrial parts, furniture legs, and metallic items to protect them from dents.",
    basePrice: "₹1,850 / Roll",
    image: "/images/products/corrugated-rolls/image.png",
    gallery: ["/images/products/corrugated-rolls/image.png"],
    specs: {
      "Paper Composition": "120 GSM linear board / 100 GSM flute",
      "Flute density": "45 flutes/foot",
      "Roll Length": "15 meters standard",
      "Roll Weight": "25 kg average",
    },
    options: {
      widths: ["1.0m", "1.2m", "1.5m"],
      thicknesses: ["2-ply Single Face"],
      colors: ["Natural Brown"],
    },
    applications: ["Industrial metal gear wrapping", "Moving and packing surface wrap", "Glass panel interleaving wrap"],
    visualGradients: "from-rose-400 to-pink-500",
  },
  {
    id: "edge-protector",
    title: "Edge Protector",
    category: "protective",
    tag: "Edge",
    blurb: "Heavy-duty paperboard angle board edge protectors.",
    longDesc: "L-shaped laminated paperboard edge protectors. Reinforces pallet vertical stack integrity, prevents strap cutting damage on carton corners, and locks columns of boxes during strapping.",
    basePrice: "₹35 / Piece",
    image: "/images/products/edge-protector/image.png",
    gallery: ["/images/products/edge-protector/image.png"],
    specs: {
      "Material composition": "Multi-layer laminated paperboard",
      "Thickness Tolerance": "+/- 0.2 mm",
      "Flexural Strength": "High compression tolerance",
      "Water barrier": "Slight moisture repellent coating",
    },
    options: {
      widths: ["50x50 mm", "75x75 mm"],
      thicknesses: ["3 mm", "4 mm", "5 mm"],
      colors: ["Kraft Brown"],
    },
    applications: ["Pallet vertical stacking reinforcement", "Box corner protectors under strap tension", "Export bundle packaging stabilization"],
    visualGradients: "from-rose-400 to-pink-500",
  },

  // --- TAPES ---
  {
    id: "bopp-tapes",
    title: "BOPP Tapes",
    category: "tapes",
    tag: "BOPP",
    blurb: "Clear and brown pressure-sensitive acrylic packaging tape.",
    longDesc: "High performance BOPP backing film coated with special pressure-sensitive acrylic adhesive. Extruded with strict caliper controls to guarantee instant bonding on cartons without peeling.",
    basePrice: "₹45 / Roll",
    image: "/images/products/bopp-tapes/image.png",
    gallery: ["/images/products/bopp-tapes/image.png"],
    specs: {
      "Film Caliper": "23 Micron BOPP Film",
      "Adhesive type": "Acrylic emulsion glue coating",
      "Adhesive thickness": "20 Micron",
      "Elongation limit": "140% break threshold",
    },
    options: {
      widths: ["48 mm", "72 mm"],
      thicknesses: ["40 Micron", "45 Micron", "50 Micron"],
      colors: ["Transparent Clear", "Amber Brown"],
    },
    applications: ["Corrugated box sealing", "Manual dispenser taping runs", "Automatic tape machine sealing"],
    visualGradients: "from-violet-400 to-fuchsia-500",
  },
  {
    id: "printed-bopp-tapes",
    title: "Printed BOPP Tapes",
    category: "tapes",
    tag: "Printed",
    blurb: "Custom-printed packaging tape with logo prints.",
    longDesc: "BOPP adhesive tape customized with company names, logos, or warning warnings. Reinforces product safety and security, acting as an instant pilferage-indicator seal.",
    basePrice: "₹75 / Roll",
    image: "/images/products/printed-bopp-tapes/image.png",
    gallery: ["/images/products/printed-bopp-tapes/image.png"],
    specs: {
      "Print cycle length": "150mm / 220mm cycle print",
      "Ink bonding": "UV ink print no wear",
      "Adhesion shear": "Over 24 hours constant tack",
      "Roll length": "65 meters / 130 meters",
    },
    options: {
      widths: ["48 mm", "72 mm"],
      thicknesses: ["45 Micron", "50 Micron"],
      colors: ["White base with red ink", "Yellow base with black ink", "Custom logos"],
    },
    applications: ["E-commerce shipping box security", "Premium brand identity packaging", "Warning box sealing"],
    visualGradients: "from-violet-400 to-fuchsia-500",
  },
  {
    id: "coloured-bopp-tapes",
    title: "Coloured BOPP Tapes",
    category: "tapes",
    tag: "Coloured",
    blurb: "Multi-color self-adhesive tapes for carton identification.",
    longDesc: "High opacity colored BOPP self-adhesive tapes. Excellent for inventory management, sorting lines categorization, and color coding box dispatches in large fulfillment warehouses.",
    basePrice: "₹55 / Roll",
    image: "/images/products/coloured-bopp-tapes/image.png",
    gallery: ["/images/products/coloured-bopp-tapes/image.png"],
    specs: {
      "Color pigment style": "Full body block color",
      "Tack rating": "Instant adhesion",
      "Roll width tolerance": "+/- 0.5 mm",
      "Roll Core": "3 inch standard paper core",
    },
    options: {
      widths: ["48 mm"],
      thicknesses: ["45 Micron"],
      colors: ["Red", "Yellow", "Blue", "Green", "Orange"],
    },
    applications: ["Inventory box color classification", "High visibility parcel marking", "Warehouse cargo batching"],
    visualGradients: "from-violet-400 to-fuchsia-500",
  },
  {
    id: "silicon-tapes",
    title: "Silicon Tapes",
    category: "tapes",
    tag: "Silicon",
    blurb: "High temperature self-fusing silicon rubber sealing tapes.",
    longDesc: "Premium self-fusing silicone rubber sealing tape. Operates without adhesive by fusing to itself when wrapped under tension. Provides waterproof, airtight, and high temperature resistant seal over pipes and cables.",
    basePrice: "₹450 / Roll",
    image: "/images/products/silicon-tapes/image.png",
    gallery: ["/images/products/silicon-tapes/image.png"],
    specs: {
      "Working Temp limit": "-50°C to 260°C",
      "Fusing Speed": "Immediate self-bonding (fuses in 24h)",
      "Dielectric Strength": "8 kV electrical shield",
      "Moisture rating": "100% waterproof and airtight",
    },
    options: {
      widths: ["25 mm", "50 mm"],
      thicknesses: ["0.5 mm", "1.0 mm"],
      colors: ["Jet Black", "Silicone Red"],
    },
    applications: ["Emergency leak wrapping", "High voltage cable insulation wrapping", "Industrial pipe thread seals"],
    visualGradients: "from-violet-400 to-fuchsia-500",
  },

  // --- PALLET WRAPPING ---
  {
    id: "manual-stretch-film",
    title: "Manual Stretch Film",
    category: "pallet-wrapping",
    tag: "Manual",
    blurb: "Pre-stretched manual hand-grade stretch wrap rolls.",
    longDesc: "Pre-stretched and standard hand-wrapping stretch films. High puncture resistance prevents tearing on box corners. Lightweight roll profile reduces worker fatigue during manual pallet wrapping.",
    basePrice: "₹850 / Roll",
    image: "/images/products/manual-stretch-film/image.png",
    gallery: ["/images/products/manual-stretch-film/image.png"],
    specs: {
      "Stretch Ratio": "Up to 150% manual limit",
      "Cling index": "One-sided tackiness (leaves no residue)",
      "Core Size": "3 inch standard cardboard core",
      "Roll weight": "2.4 kg average",
    },
    options: {
      widths: ["450 mm", "500 mm"],
      thicknesses: ["12 Micron", "15 Micron", "19 Micron"],
      colors: ["Ultra Clear Tint", "Opaque Jet Black"],
    },
    applications: ["Manual pallet wrap runs", "Irregular shaped load binding", "Dust and water proof wrap coating"],
    visualGradients: "from-yellow-400 to-amber-500",
  },
  {
    id: "machine-stretch-film",
    title: "Machine Stretch Film",
    category: "pallet-wrapping",
    tag: "Machine",
    blurb: "High-performance power pre-stretch machine wrap film rolls.",
    longDesc: "Cast co-extruded machine stretch film rolls. Designed to stretch up to 300% on automatic powered pre-stretch turntable wrappers. Low noise unwind and high puncture resistance.",
    basePrice: "₹170 / kg",
    image: "/images/products/machine-stretch-film/image.png",
    gallery: ["/images/products/machine-stretch-film/image.png"],
    specs: {
      "Stretch Capability": "250% - 300% power stretch",
      "Roll Weight": "15 kg standard machine roll",
      "Puncture resistance": "Extremely high dart rating",
      "Roll core type": "Heavy duty machine core",
    },
    options: {
      widths: ["500 mm"],
      thicknesses: ["23 Micron", "25 Micron", "29 Micron"],
      colors: ["Crystal Clear"],
    },
    applications: ["Automatic pallet wrappers", "High volume packing warehouse runs", "Secure export cargo load wrap"],
    visualGradients: "from-yellow-400 to-amber-500",
  },
  {
    id: "pallet-cover",
    title: "Pallet Cover",
    category: "pallet-wrapping",
    tag: "Pallet Cover",
    blurb: "Heavy gauge dustproof LDPE pallet hood covers.",
    longDesc: "Gusseted LDPE pallet bags. Slipped over stacked pallets before stretch wrapping to provide complete 5-side moisture, dust, and rain protection for outdoor warehousing.",
    basePrice: "₹240 / kg",
    image: "/images/products/pallet-cover/image.png",
    gallery: ["/images/products/pallet-cover/image.png"],
    specs: {
      "Material Style": "Gusseted LDPE Hood bag",
      "Dust protection": "100% dust proof shield",
      "Water barrier": "Waterproof LDPE surface",
      "Format": "Pre-cut bags on roll",
    },
    options: {
      widths: ["Standard Pallet (1200x1000x1500mm)", "Extended Pallet (1200x1000x2000mm)"],
      thicknesses: ["80 Micron", "100 Micron", "120 Micron"],
      colors: ["Translucent Clear", "Opaque Black"],
    },
    applications: ["Outdoor pallet warehousing protection", "Chemical bulk bag covers", "Rain proof cargo shipping preparation"],
    visualGradients: "from-yellow-400 to-amber-500",
  },
  {
    id: "pallet-liner",
    title: "Pallet Liner",
    category: "pallet-wrapping",
    tag: "Pallet Liner",
    blurb: "Slip-resistant corrugated and plastic bottom liner sheets.",
    longDesc: "Placed on the wooden pallet base before stacking cartons. Protects bottom carton layers from nail punctures, splinters, moisture rising from wet wooden blocks, and slippage during cargo transit.",
    basePrice: "₹18 / Sheet",
    image: "/images/products/pallet-liner/image.png",
    gallery: ["/images/products/pallet-liner/image.png"],
    specs: {
      "Composition": "Heavy Kraft Cardboard / Corrugated plastic profile",
      "Slip Rating": "High slip-resistant surface coating",
      "Standard size": "1200 x 1000 mm",
      "Waterproofing": "Poly-laminated water barrier options",
    },
    options: {
      widths: ["1200 x 1000 mm"],
      thicknesses: ["350 GSM Paperboard", "3mm Corrugated plastic"],
      colors: ["Kraft Brown", "Grey plastic"],
    },
    applications: ["Pallet bottom layer board", "Stack stabilization interleaving", "Carton moisture barrier protector"],
    visualGradients: "from-yellow-400 to-amber-500",
  }
];

export const initialMachines = [
  {
    model: "WP-SWM",
    name: "Shrink Wrap Machine",
    tagline: "Continuous high-speed shrink wrapping sealer and tunnel integration.",
    desc: "Continuous L-bar sealing machine synchronized with a hot-air recirculation shrink tunnel. Delivers fast shrink wrapping for retail products, cosmetics, boxes, and stationery bundle packs.",
    image: "/images/machines/shrink-wrap-machine/image.png",
    specs: [
      { label: "Throughput Speed", value: "35-45 packs/min" },
      { label: "Max Sealer Size", value: "550 x 450 mm" },
      { label: "Electrical Input", value: "4.2 kW, 3-Phase" },
      { label: "Pneumatic Input", value: "6 Bar, 140 L/min" },
    ],
    highlights: ["PLC Touchscreen Control", "Continuous L-sealer", "Recirculation shrink tunnel", "CE Certified compliance"],
  },
  {
    model: "WP-BM",
    name: "Bundling Machine",
    tagline: "Automated collation bundling for cans, jars, and cartons.",
    desc: "Heavy-duty sleeve wrapper and bundling machine designed to collate and wrap mineral water bottles, beverage cans, or food jars with collation shrink films, eliminating carton boxes.",
    image: "/images/machines/bundling-machine/image.png",
    specs: [
      { label: "Collation Speed", value: "12-18 bundles/min" },
      { label: "Max Wrapping Width", value: "600 mm" },
      { label: "Film Material type", value: "LDPE Collation shrink film" },
      { label: "Electrical Load", value: "18 kW, 3-Phase" },
    ],
    highlights: ["Sleeve wrapping seal", "Heavy LDPE collation ready", "Automatic collation sorter", "Stitchless heating tunnel"],
  },
  {
    model: "WP-FPM",
    name: "Flow Pack Machine",
    tagline: "Horizontal flow wrapping machine for packaging products in pouches.",
    desc: "Industrial horizontal form-fill-seal (HFFS) packaging machine. Wraps individual products like bakery items, soap bars, courier envelopes, and stationery items inside pillow-packs.",
    image: "/images/machines/flow-pack-machine/image.png",
    specs: [
      { label: "Wrapping Rate", value: "40-150 packs/min" },
      { label: "Pouch Length range", value: "90mm to 400mm" },
      { label: "Pouch Width limit", value: "Max 180mm" },
      { label: "Electrical Input", value: "2.8 kW, Single-Phase" },
    ],
    highlights: ["Horizontal HFFS form-fill", "Dual-frequency converter controls", "Photo-cell tracking sensor", "Anti-cutting safety protection"],
  },
  {
    model: "WP-VM",
    name: "Vacuum Machine",
    tagline: "Industrial chamber vacuum packaging machine for food and perishables.",
    desc: "Heavy-duty double chamber vacuum packaging machine. Extracts oxygen and seals food pouches, extending the storage shelf life of FMCG food items, electronics, and pharmaceuticals.",
    image: "/images/machines/vacuum-machine/image.png",
    specs: [
      { label: "Vacuum Cycle speed", value: "20-40 seconds" },
      { label: "Sealing Bar size", value: "600 mm length" },
      { label: "Vacuum Pump load", value: "40 m³/h capacity" },
      { label: "Electrical Input", value: "1.5 kW, Single-Phase" },
    ],
    highlights: ["Double chamber efficiency", "Stainless steel construction", "Microprocessor controller", "Gas flushing packaging option"],
  }
];

export const initialArticles = [
  {
    tag: "Engineering",
    date: "Mar 2026",
    title: "Choosing between PP and PET strap: a load-vs-cost framework",
    excerpt: "A simple decision tree — based on 6 years of mill data — that helps procurement pick the right strap for the right load, without overspending.",
    read: "6 min read",
    featured: true,
    slug: "pp-vs-pet-strap-framework",
    body: "Polypropylene (PP) and Polyester (PET) straps serve distinct purposes in industrial packaging. While PP strap is highly elastic and suited for light-to-medium bundles that expand/contract, PET strap offers superior tension retention and impact resistance, replacing steel strapping for heavy palletized loads.",
    image: "/images/desktop/portfolio/quality_featured.png",
  },
  {
    tag: "Sustainability",
    date: "Feb 2026",
    title: "Mono-material films and the road to recyclable e-commerce packaging",
    excerpt: "Why multi-layer laminate plastics are a recycling nightmare and how new oriented films enable single-stream recycling compatibility.",
    read: "8 min read",
    featured: false,
    slug: "mono-material-recyclable-films",
    body: "Multi-layer packaging has traditionally combined different plastic types, making them impossible to recycle together. Our latest mono-material LDPE and POF shrink/stretch films provide the same barrier properties and tensile strength while remaining fully compatible with standard single-stream recycling loops, allowing your buyers to meet strict plastic waste compliance.",
    image: "/images/desktop/portfolio/sustainability_featured.png",
  },
  {
    tag: "Operations",
    date: "Jan 2026",
    title: "How we hit 98.4% on-time dispatch in 2025 — a playbook",
    excerpt: "A look inside Winner Pack's Dasna hub operations, vehicle coordination algorithms, and WhatsApp integrations.",
    read: "5 min read",
    featured: false,
    slug: "on-time-dispatch-playbook-2025",
    body: "At Winner Pack, delivery is a key product feature. By coordinating Dasna plants with localized distribution hubs, pre-staging high-volume SKU inventory, and setting automated carrier assignment workflows linked directly to buyer WhatsApp alerts, we sustained a 98.4% rolling on-time delivery rate. Here is our operational playbook.",
    image: "/images/desktop/portfolio/dispatch_featured.png",
  },
];

const defaultSlides = [
  {
    title: "Heavy-duty packaging for zero-transit damage.",
    subtitle: "High-cling stretch films, virgin PP/PET strapping, and custom labels manufactured in Ghaziabad and shipped directly to your plant.",
    image: "/images/desktop/hero-slider/slide-1.png",
    desktopMediaUrl: "/images/desktop/hero-slider/slide-1.png",
    mobileMediaUrl: "/images/mobile/hero-slider/slide-1.png",
  },
  {
    title: "Engineered to keep production running.",
    subtitle: "We manufacture high-tensile packaging materials and supply automated machinery to optimize your end-of-line packaging operations.",
    image: "/images/desktop/hero-slider/slide-2.png",
    desktopMediaUrl: "/images/desktop/hero-slider/slide-2.png",
    mobileMediaUrl: "/images/mobile/hero-slider/slide-2.png",
  },
  {
    title: "Direct dispatch across India.",
    subtitle: "From our manufacturing unit in Ghaziabad, UP, we ship premium quality secondary and tertiary packaging materials directly to 1,200+ pin codes.",
    image: "/images/desktop/hero-slider/slide-3.png",
    desktopMediaUrl: "/images/desktop/hero-slider/slide-3.png",
    mobileMediaUrl: "/images/mobile/hero-slider/slide-3.png",
  },
  {
    title: "Tailored specs, competitive pricing.",
    subtitle: "Get standard or custom gauge materials, certified quality checks, and pricing that aligns with your annual procurement budget.",
    image: "/images/desktop/hero-slider/slide-4.png",
    desktopMediaUrl: "/images/desktop/hero-slider/slide-4.png",
    mobileMediaUrl: "/images/mobile/hero-slider/slide-4.png",
  }
];

const defaultRightBanner = "/images/desktop/hero-slider/right-banner.png";
const defaultMobileRightBanner = "/images/mobile/hero-slider/right-banner.png";

const defaultAbout = {
  tagline: "Pioneering Industrial Packaging & Labeling Solutions",
  para1: "Winner Pack Technologies Pvt. Ltd. supplies environment-friendly secondary and tertiary packaging materials and machinery. Guided by our motto \"We Serve To Deserve\", we supply premium quality solutions tailored to your operational needs.",
  para2: "From Ghaziabad, UP, we specialize in high-cling BOPP tapes, strapping rolls, POF/PVC shrink films, protective packaging, and industrial machinery, serving the pharmaceutical, cosmetics, food/FMCG, and stationery industries.",
  stats: [
    { value: "8+", label: "Years in business" },
    { value: "6", label: "Product categories" },
    { value: "20+", label: "Product lines" },
    { value: "100%", label: "Customer commitment" }
  ]
};

const defaultUsps = [
  {
    title: "Zero catalog forcing",
    text: "We specify to the exact width, gauge, and formulation your line speed needs — not the nearest match we have in stock.",
    icon: "Tag"
  },
  {
    title: "Guaranteed tracking",
    text: "Our strap rolls are extruded to maintain straightness, eliminating feed jams in automated high-speed strapping machines.",
    icon: "Layers"
  },
  {
    title: "High-cling formulation",
    text: "WPT stretch films use premium linear low-density polyethylene for maximum load-holding force with minimal wrap layers.",
    icon: "Disc3"
  },
  {
    title: "In-house quality check",
    text: "Every batch of BOPP tape and shrink rolls goes through rigorous elongation, tensile strength, and adhesive testing.",
    icon: "Shield"
  },
  {
    title: "Eco-friendly options",
    text: "FSC certified recyclable paper mailers and biodegradable films to help your plant meet compliance and ESG mandates.",
    icon: "Leaf"
  },
  {
    title: "Direct from Ghaziabad",
    text: "No distributor markups. We manufacture, warehouse, and dispatch directly to save your operations 12-18% annually.",
    icon: "Globe2"
  }
];

const defaultClients = [
  { name: "Lava", logo: "/Brand_logo/lava.png" },
  { name: "Vivo", logo: "/Brand_logo/vivo.png" },
  { name: "Noise", logo: "/Brand_logo/noise.png" },
  { name: "Fire-Boltt", logo: "/Brand_logo/firebolt.png" }
];

const defaultSteps = [
  {
    n: "01",
    phase: "Discovery",
    title: "Tell us your line.",
    body: "Share your SKU, payload profile and dispatch rhythm. Our team scopes the right strapping, shrink film or courier packaging for your operation.",
    deliverable: "Requirement scoping"
  },
  {
    n: "02",
    phase: "Sample",
    title: "Material in your hands.",
    body: "We share a sample of the exact gauge, width and grade — PP/PET strap, shrink film or bubble roll — so you can test it before committing.",
    deliverable: "Sample dispatch"
  },
  {
    n: "03",
    phase: "Trial",
    title: "Line qualification.",
    body: "For strapping, shrink wrapping and taping machines, our team helps set up and tune equipment against your throughput and operator handling.",
    deliverable: "Machine setup support"
  },
  {
    n: "04",
    phase: "Order",
    title: "Confirmed pricing.",
    body: "We quote based on your volume and material spec, and confirm terms before production and delivery are scheduled.",
    deliverable: "Quote & confirmation"
  },
  {
    n: "05",
    phase: "Dispatch",
    title: "Delivered from Ghaziabad.",
    body: "Orders are dispatched from our Ghaziabad, UP base and delivered to your site as per the scheduled timeframe.",
    deliverable: "Scheduled delivery"
  },
  {
    n: "06",
    phase: "Support",
    title: "Ongoing service.",
    body: "We stay on for spares, machine servicing and repeat supply of strap rolls, films and packaging tools as your needs continue.",
    deliverable: "Service & repeat supply"
  }
];

const defaultIndustries = [
  { name: "Electronics", image: "/images/desktop/industries/electronics_industry.png" },
  { name: "Cosmetics", image: "/images/desktop/industries/cosmetics_industry.png" },
  { name: "Food & FMCG", image: "/images/desktop/industries/food_fmcg_industry.png" },
  { name: "Stationery", image: "/images/desktop/industries/stationery_industry.png" },
  { name: "E-commerce & Logistics", image: "/images/desktop/industries/ecommerce_logistics_industry.png" }
];

export const fallbackData = {
  slides: defaultSlides,
  rightBanner: defaultRightBanner,
  mobileRightBanner: defaultMobileRightBanner,
  about: defaultAbout,
  usps: defaultUsps,
  clients: defaultClients,
  steps: defaultSteps,
  industries: defaultIndustries
};
