'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowUp, ArrowDown, Plus, Trash2, Save, ExternalLink, Upload } from 'lucide-react';
import { apiFetch } from '@/lib/api';
import { invalidateContent } from '@/lib/content-cache';
import type { ContentSection } from '@/lib/admin/sections';

const labels:Record<string,string>={slides:'Carousel slides',rightBanner:'Desktop showcase image',about:'Company introduction',tagline:'Headline',para1:'Introduction',para2:'Supporting paragraph',image1:'First plant image',image2:'Second plant image',usps:'Customer benefits',solutionsData:'Packaging capabilities',question:'Benefit title',solution:'Supporting headline',challenge:'Description',partnerHeader:'Section heading',tag:'Eyebrow text',ctaText:'Button label',ctaLink:'Button destination',desktopMediaUrl:'Desktop image',mobileMediaUrl:'Mobile image',imageSrc:'Certification image',mainHero:'Gallery hero',portraits:'Portrait photographs',landscapes:'Landscape photographs',phone2:'Secondary phone',desc:'Description',whatsapp:'WhatsApp number',slot:'Display number'};
function label(key:string){return labels[key]||key.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());}
function isImage(key:string){return /image|logo|banner|mediaurl/i.test(key);}
function blank(value:any):any{if(Array.isArray(value))return value.map(blank);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([key,v])=>[key,key==='id'?`item-${Date.now()}`:blank(v)]));return typeof value==='number'?0:typeof value==='boolean'?true:'';}
export function useUnsavedWarning(dirty:boolean){useEffect(()=>{if(!dirty)return;const unload=(event:BeforeUnloadEvent)=>{event.preventDefault();};const click=(event:MouseEvent)=>{const anchor=(event.target as HTMLElement).closest('a');if(anchor&&anchor.target!=='_blank'&&anchor.href!==window.location.href&&!window.confirm('Leave this page and discard your unpublished changes?')){event.preventDefault();event.stopPropagation();}};window.addEventListener('beforeunload',unload);document.addEventListener('click',click,true);return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',click,true);};},[dirty]);}
function Field({name,value,onChange}:{name:string;value:any;onChange:(value:any)=>void}){
 const [uploading,setUploading]=useState(false);const [error,setError]=useState('');
 if(Array.isArray(value))return <div className="admin-field wide"><div className="admin-item-head"><h3>{label(name)} <span className="admin-muted">· {value.length} items</span></h3><button type="button" className="admin-button" onClick={()=>onChange([...value,blank(value[0]??{title:'',image:''})])}><Plus/>Add item</button></div>{value.map((item,index)=><div className="admin-item" key={index}><div className="admin-item-head"><h3>{String(index+1).padStart(2,'0')} · {item?.title||item?.name||item?.heading||item?.question||label(name)}</h3><div className="admin-actions"><button type="button" className="admin-button !p-2" aria-label={`Move item ${index+1} up`} disabled={index===0} onClick={()=>{const next=[...value];[next[index-1],next[index]]=[next[index],next[index-1]];onChange(next);}}><ArrowUp/></button><button type="button" className="admin-button !p-2" aria-label={`Move item ${index+1} down`} disabled={index===value.length-1} onClick={()=>{const next=[...value];[next[index+1],next[index]]=[next[index],next[index+1]];onChange(next);}}><ArrowDown/></button><button type="button" className="admin-button danger !p-2" disabled={value.length<=1} aria-label={`Remove item ${index+1}`} onClick={()=>{if(window.confirm('Remove this item? Changes take effect when published.'))onChange(value.filter((_,i)=>i!==index));}}><Trash2/></button></div></div><Field name="item" value={item} onChange={next=>onChange(value.map((v,i)=>i===index?next:v))}/></div>)}</div>;
 if(value&&typeof value==='object')return <fieldset className="admin-field wide"><legend className="sr-only">{label(name)}</legend><div className="admin-fields">{Object.entries(value).filter(([key])=>!['id','_id','__v','createdAt','updatedAt'].includes(key)).map(([key,v])=><Field key={key} name={key} value={v} onChange={next=>onChange({...value,[key]:next})}/>)}</div></fieldset>;
 const image=isImage(name);const long=/description|para|challenge|blurb|address/i.test(name)||String(value??'').length>160;
 async function upload(file:File|undefined){if(!file)return;setUploading(true);setError('');try{const body=new FormData();body.append('file',file);const res=await apiFetch('/api/upload',{method:'POST',body});const data=await res.json();if(!res.ok||!data.url)throw Error(data.error||'Upload failed.');onChange(data.url);}catch(err){setError(err instanceof Error?err.message:'Upload failed.');}finally{setUploading(false);}}
 return <div className={`admin-field ${long?'wide':''}`}><label><span className="block text-[11px] font-semibold text-[#696175] mb-2">{label(name)}</span>{long?<textarea value={value??''} onChange={e=>onChange(e.target.value)}/>:<input type={typeof value==='number'?'number':'text'} value={value??''} onChange={e=>onChange(typeof value==='number'?Number(e.target.value):e.target.value)}/>}</label>{image&&<><div className="admin-field-preview">{value?<img src={value} alt={`${label(name)} preview`}/>:<span className="admin-muted">Choose an image</span>}</div><label className="admin-button mt-2"><Upload/>{uploading?'Uploading…':'Upload image'}<input type="file" className="!hidden" accept="image/jpeg,image/png,image/webp,image/avif" disabled={uploading} onChange={e=>void upload(e.target.files?.[0])}/></label><p className="admin-muted mt-1">JPEG, PNG, WebP or AVIF · up to 10 MB</p></>}{error&&<p role="alert" className="admin-notice error">{error}</p>}</div>;
}
export default function ContentEditor({section}:{section:ContentSection}){
 const [data,setData]=useState<Record<string,any>>(section.defaults);const [original,setOriginal]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [loaded,setLoaded]=useState(false);
 const dirty=loaded&&JSON.stringify(data)!==original;useUnsavedWarning(dirty);
 async function load(){setLoading(true);setError('');try{const res=await apiFetch(`/api/content?key=${encodeURIComponent(section.key)}`,{cache:'no-store'});if(!res.ok)throw Error('Could not load this section. Please try again.');const json=await res.json();const content=json?.data??json;const next={...section.defaults};for(const key of Object.keys(next)){if(content[key]!==undefined)next[key]=typeof next[key]==='object'&&!Array.isArray(next[key])?{...next[key],...content[key]}:content[key];}setData(next);setOriginal(JSON.stringify(next));setLoaded(true);}catch(err){setError(err instanceof Error?err.message:'Could not load section.');}finally{setLoading(false);}}
 useEffect(()=>{void load();},[section.id]);
 async function save(){setSaving(true);setError('');setMessage('');try{const before=JSON.parse(original);const patch=Object.fromEntries(Object.entries(data).filter(([key,value])=>JSON.stringify(value)!==JSON.stringify(before[key])));const res=await apiFetch('/api/content',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:section.key,data:patch})});if(!res.ok){const json=await res.json();throw Error(json.error||'Could not publish changes.');}invalidateContent(section.key);setOriginal(JSON.stringify(data));setMessage('Changes published. Open the website to review your update.');}catch(err){setError(err instanceof Error?err.message:'Could not publish.');}finally{setSaving(false);}}
 return <><Link href="/admin/website" className="admin-row-link mb-6"><ArrowLeft size={14}/>All website sections</Link><div className="admin-page-heading"><div><div className="admin-eyebrow">{section.home?'Homepage content':'Website content'}</div><h1 className="admin-heading">{section.title}</h1><p className="admin-description">{section.description}</p></div><a href={section.preview} target="_blank" rel="noreferrer" className="admin-button"><ExternalLink/>View on website</a></div>
 {error&&<div role="alert" className="admin-notice error">{error}{!loaded&&<button className="underline ml-2" onClick={load}>Try again</button>}</div>}{message&&<p role="status" className="admin-notice">{message}</p>}
 {loading?<div className="admin-panel admin-empty" role="status">Loading section content…</div>:loaded&&<><div className="admin-editor-grid"><fieldset disabled={saving} className="min-w-0"><div className="admin-panel"><div className="admin-panel-header"><h2>Content & imagery</h2><span className={`admin-badge ${dirty?'orange':'gray'}`}>{dirty?'Unpublished changes':'Up to date'}</span></div><div className="admin-panel-body admin-fields">{Object.entries(data).map(([key,value])=><Field key={key} name={key} value={value} onChange={next=>{setData(prev=>({...prev,[key]:next}));setMessage('');}}/>)}</div></div></fieldset><aside className="admin-panel admin-help"><h3>Make every detail count.</h3><p>Use clear headings and sharp images that match your current products and facilities.</p><h3>Publishing changes</h3><p>Edits stay here until you publish. Only this section is updated; other website sections keep their content.</p>{section.home&&<><h3>Section visibility</h3><p>Show or hide this whole section from the homepage manager.</p><Link href="/admin/website" className="admin-row-link">Manage visibility →</Link></>}{section.id==='hero'&&<p className="mt-4">The homepage displays the first four slides. Move your preferred slides to the top.</p>}</aside></div><div className="admin-savebar"><span className="admin-muted">{dirty?'You have unpublished changes.':'All changes are published.'}</span><div className="admin-actions"><button className="admin-button" disabled={!dirty||saving} onClick={()=>{if(window.confirm('Discard unpublished changes?')){setData(JSON.parse(original));setMessage('');}}}>Discard</button><button className="admin-button primary" disabled={!dirty||saving} onClick={save}><Save/>{saving?'Publishing…':'Publish changes'}</button></div></div></>}
 </>;
}
