'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import { ArrowRight, Eye, EyeOff } from 'lucide-react';
import { apiFetch } from '@/lib/api';
export default function Login(){
  const router=useRouter();const [password,setPassword]=useState('');const [show,setShow]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{const res=await apiFetch('/api/admin/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!res.ok){const data=await res.json();throw Error(data.error||'Could not sign in.');}const next=new URLSearchParams(window.location.search).get('next');router.replace(next?.startsWith('/admin/')&&!next.startsWith('/admin/login')?next:'/admin');router.refresh();}catch(err){setError(err instanceof Error?err.message:'Could not connect. Please try again.');}finally{setBusy(false);}}
  return <div className="admin-login"><div className="admin-login-brand"><Link href="/" className="admin-brand !p-0"><img src="/logo.png" alt=""/><span>Winner Pack<small>Technologies Pvt. Ltd.</small></span></Link><div><div className="admin-eyebrow !text-orange-300">Your website, thoughtfully managed</div><h1>Great packaging.<br/><span className="text-orange-300">A stronger presence.</span></h1><p>One workspace for your products, stories and the customers who come next.</p></div><small className="text-violet-300 text-xs">We serve to deserve.</small></div><div className="admin-login-form"><form onSubmit={submit}><div className="admin-eyebrow">Website studio</div><h2>Welcome back.</h2><p className="admin-muted mb-8">Sign in to manage the Winner Pack website.</p><label className="admin-field"><span>Admin password</span><div className="relative"><input type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} className="!pr-12" placeholder="Enter your password"/><button type="button" className="absolute right-3 top-3" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label>{error&&<p role="alert" className="admin-notice error">{error}</p>}<button disabled={busy} className="admin-button primary w-full mt-6 !py-3">{busy?'Signing in…':'Sign in'}<ArrowRight/></button><p className="admin-muted mt-6">Use the password configured for your administrator account.</p><Link href="/" className="admin-row-link mt-8">← Back to website</Link></form></div></div>;
}
